version: "3"

env:
  AWS_REGION: ap-northeast-1

tasks:
  shell:
    cmds:
      - "{{.CLI_ARGS}}"

  run:
    cmds:
      - watchexec -r -e go -- go run ./...

  deploy:
    cmds:
      - terraform init
      - terraform apply -auto-approve

  destroy:
    cmds:
      - terraform init
      - terraform destroy -auto-approve
